apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-service
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      -  name: customer-service
         image: nevenc/customer-service-k8s:1.0.1
         ports:
         - containerPort: 8080

