apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
data:
  database.username: dXNlcg==
  database.password: cGFzc3dvcmQ=
  datasource.url: amRiYzpteXNxbDovLzEwNC4xNTUuMjIuMjE0L2N1c3RvbWVycw==
  
